# Generated by Django 6.0.3 on 2026-03-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('shaxsiy', 'Shaxsiy'), ('ommaviy', 'Ommaviy')], default='shaxsiy'),
        ),
    ]
